version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/rentedge

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user
